### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jaredledvina** [halyard/puppet-dotfiles#12]
Makes bootstrapping a bit easier such that I can get to local `dev` versions, would like to use the commits added since the last release: https://github.com/halyard/puppet-dotfiles/compare/0.2.7...HEAD

**Comment by akerl** [comment]
I feel like I'm missing something; those commits don't have any functionality changes, just dep versions and meta, right?

**Comment by jaredledvina** [comment]
Ah, yeah, I messed up, this one is fine, https://github.com/halyard/puppet-halyard/issues/7 is the one that would help.
